### ISSUE TITLE
Energy bolas slow down when put in pockets 

### ISSUE THREAD

**Issue by coolsurf6** [austation/austation#1319]
Issue reported from  Round ID: 3263 (AuStation 13 [AUSTRALIA/OCEANIA][BEESTATION EDITION])
Reporting client version: 513.1508

![NiceSpeed](https://user-images.githubusercontent.com/16472329/74718563-33678280-527e-11ea-81d5-c4ce36a8104b.gif)
(Small gif I know)

When ever you mess with bolas, for some reason my character just stopped moving at the normal speed. I was able to figure out that the bolas were doing it and could replicate it when putting the bola into your pocket, then taking it out again. 

The speed that the character was going was slightly faster than if the bola was activated on their leg, so I'm not sure why it was happening.

**Comment by MCterra10** [comment]
There's a potentially related PR that might fix this that I just merged. Can you confirm the bug is still an issue?

**Comment by coolsurf6** [comment]
Looks like the issue was fixed with the PR @MCterra10. Not sure what the reason of the bug was but it seems to be fixed now.

**Comment by MCterra10** [comment]
Uhh there was a feature that made it so items that applied slowdown when worn would slow you down when held. The idea was to discourage tactical space suit removal. It got reverted yesterday
