### ISSUE TITLE
Mentors can't use MSAY (Default F4 bind)

### ISSUE THREAD

**Issue by coolsurf6** [austation/austation#1328]
Issue reported from  Round ID: 3284 (AuStation 13 [AUSTRALIA/OCEANIA][BEESTATION EDITION])
Reporting client version: 513.1508

Terra knows about this already but I wanted to make an actual issue on the github so I can get updates. Msay can be used by typing in "msay" and hitting space in the chat bar but there is a keybind accessible only to admins to use msay. 

![image](https://user-images.githubusercontent.com/16472329/75033760-55b80500-54f7-11ea-8170-2494e1b618a9.png)

Probably just a permission error or something. Not sure.

**Comment by MCterra10** [comment]
Thanks for the reminder, will look into it soon

**Comment by MCterra10** [comment]
Pushing a fix in a sec

**Comment by MCterra10** [comment]
should be fixed in 05098d8f51c0ccf0fe388414fd7db46510eb2b95
can you confirm if it's working or not

**Comment by MCterra10** [comment]
Resolved
