### ISSUE TITLE
IPC brain glitch

### ISSUE THREAD

**Issue by BowStache** [austation/austation#2316]
## Round ID: 5275

I don't know how to use github, but are you really gonna take down a bug request? yeah nah yeah nah

So basically if you take out an ipc brain and then put it back in, your brain goes to the coordinates 0,0,0 on your screen, on other peoples screens your character stands back up and does nothing. This has happened every single time i've had my brain taken out and then put back into my corpse, don't know if it works with other corpses other then your own. pls fix

**Comment by DungeonPenguin** [comment]
mmi?

**Comment by BowStache** [comment]
> mmi?

Nope, just the ipc brain

**Comment by Mick1299** [comment]
Does the same thing happen if you implant an ipc brain into another ipc body? Or just straight up another body?

**Comment by BowStache** [comment]
Any attempts to but an ipc brain in any body will cause the glitch
![image](https://user-images.githubusercontent.com/58099573/95155440-deae5300-07df-11eb-8afa-442dd3f18af8.png)

**Comment by TheFakeElon** [comment]
Bugs preferably should be reported upstream

**Comment by BowStache** [comment]
no idea what that means 😎

**Comment by TheFakeElon** [comment]
Make a bug report on the bee station hornet github :)
