### ISSUE TITLE
String highlighting skips every second string

### ISSUE THREAD

**Issue by mudzbe** [austation/austation#2778]
The string highlighting for the fancy chat whatever only highlights every even string, whilst every odd string is highlighted normally.

## Reproduction:

In the highlight box type a series of strings separated by commas. For example: "Jamal,Mcterra,SS13" Jamal and SS13 will be highlighted, whilst Mcterra isn't. This issue is regardless of capitalization or whether there are spaces.

**Comment by MCterra10** [comment]
Interesting. Sounds like an upstream issue though, as I haven't touched any of the chat code. I recommend you raise an issue there.

**Comment by mudzbe** [comment]
alright
