### ISSUE TITLE
Slipping on bananas doesn't cause you to slip

### ISSUE THREAD

**Issue by Ohagi-Chan** [austation/austation#335]
Issue reported from  Round ID: 2326 (AuStation 13 [AUSTRALIA/OCEANIA][100% FREE LAG])

Reporting client version: 512.1488

Stepped on bananas a few times and never slipped, though I did get the sound effect and text log stating that I slipped.

**Comment by MCterra10** [comment]
Sounds unrelated to any austation code, please open an issue on the tgstation repo
