### ISSUE TITLE
(bug report) autolathe design disks warp back to the lathe

### ISSUE THREAD

**Issue by adamok5002** [austation/austation#3424]
Issue reported from  Round ID: 7079 (AuStation 13 [AUSTRALIA/OCEANIA])

Reporting client version: 513.1542

if you place a disk into an autolathe and eject it, it will keep the option to eject it again. if you try and eject it again it will warp the disk back to the lathe from where-ever in the world it is
![image](https://user-images.githubusercontent.com/36810086/116799328-c1562300-ab3b-11eb-9a33-340ebd91a3e3.png)
![image](https://user-images.githubusercontent.com/36810086/116799333-d0d56c00-ab3b-11eb-93c8-4ca587d800b6.png)

**Comment by MCterra10** [comment]
autolathe ui is not managed by austation, because submit your report upstream at https://github.com/Beestation/Beestation-Hornet
