### ISSUE TITLE
virus statistics are bugged

### ISSUE THREAD

**Issue by nightmarish-warlord** [austation/austation#3697]
## Round ID:
7354 7355

## Reproduction:
![Screenshot (29)](https://user-images.githubusercontent.com/80289853/123541881-fbcdec00-d789-11eb-971f-3ca4e8662437.png)
![Screenshot (30)](https://user-images.githubusercontent.com/80289853/123541980-6ed76280-d78a-11eb-91f0-2552e1cd447d.png)

Symptoms stats do not add up correctly,

**Comment by MCterra10** [comment]
Investigating. I've paged lostman about the issue

**Comment by MCterra10** [comment]
confirmed upstream issue
