### ISSUE TITLE
Jobs tab on Tablets and laptops throws a Ntos error

### ISSUE THREAD

**Issue by Cooliecan** [austation/austation#4145]
## Testmerges:

Superspace shuttle merge

## Reproduction:
get a command access tablet and download the ID modifier software then try to modify the job of the ID card.

![image](https://user-images.githubusercontent.com/13284499/132176219-10c21b78-3961-4111-8d02-aa64c68882ed.png)

**Comment by MCterra10** [comment]
jobs tab is working totally fine
