### ISSUE TITLE
Radiation collectors on research mode kick out tritum cans 

### ISSUE THREAD

**Issue by Decnov81** [austation/austation#4202]
## Round ID:
7905

## Reproduction:
put tritium filled plasma tank into radiation collector that has been changed to research mode kicks the tank out

**Comment by jupyterkat** [comment]
nobody has been using it for research in ages, and you shouldn’t too

**Comment by jupyterkat** [comment]
plus you need oxygen AND tritium dumbass

**Comment by Decnov81** [comment]
> 
> 
> plus you need oxygen AND tritium dumbass

damm bro who shit in your breakfast
