### ISSUE TITLE
Slanted wallets look dumb with horizontal ID cards

### ISSUE THREAD

**Issue by Ohagi-Chan** [austation/austation#423]
Issue reported from  Round ID: 2387 (AuStation 13 [AUSTRALIA/OCEANIA][100% FREE LAG])

Reporting client version: 512.1488

**Comment by MCterra10** [comment]
Yeah this is an issue with the way I modularized the ID card sprites. I did something wrong with the wallet and the sprite didn't revert. Since there is currently another ID resprite PR open upstream I'll wait on the result of that before making any changes.

Thanks for the report!

**Comment by MCterra10** [comment]
New sprites are here, will close this shortly.
