### ISSUE TITLE
Invisible Toxin Medical kits

### ISSUE THREAD

**Issue by amidoingitright** [austation/austation#4315]
## Reproduction:
![image](https://user-images.githubusercontent.com/68313840/138554327-7f67d0e6-adad-4f29-a7c9-3cc4c758084d.png)
just walk into medbay and leftclick where the toxin medkits should be
(unknown reproduction)

**Comment by MCterra10** [comment]
![image](https://user-images.githubusercontent.com/11001588/142408636-7820376d-1dc7-40ea-b3ba-84f42dadeb0a.png)
seems fine to me

**Comment by MCterra10** [comment]
try clearing your byond cache, probably got old resource files
