### ISSUE TITLE
Metastation reactor cannot stabilize at 1k criticality 

### ISSUE THREAD

**Issue by williamcll** [austation/austation#4472]
## Reproduction:
With continued changes to atmospherics (and even before it!), the RBMK to the southeast of atmospherics does not follow standard NSV operations in order to work properly.
Under the NSV wiki that the RBMK was ported from, it should operate at a stable manner under the following conditions:
an input gas of 80/20 oxygen/plasma mix at 1500-2000kPA
A gas filter that filters nucleium (in this case, nitryl)
all pumps set to max for the cooling loop, with 1 canister of nitrogen wrenched in.

under older atmos, this would result in the RBMK reaching a thermal equilibrium at 89% reactor power. using pressure pumps will eventually cause the reactor to blow if the criticality is set to 1

Under new atmos, setting the criticality to 1 will causes the reactor to do the following under different pumps:
pressure pump at max pressure: meltdown
volume pump: blowout
straight pipe: begins cooling down to shutdown.
![image](https://user-images.githubusercontent.com/43061493/143255812-4763c6d0-9928-4be4-b6e3-6a434fb41725.png)
under straight piping with the current atmos mechanics, the way to stabilize the SM would be trial and error to find a criticality point between 0.5 to 1, for my own test this results in .595 for a canister of plasma on straight pipe and .7225 for a canister of nitrogen on straight pipe. Neither are optimal operation for a RBMK.

since I'm no expert at coding I'm not sure what's messing up the RBMK operations but even on the old mechanics, the cooling loop in space for the RBMK is also insufficient anyway since the RBMK is designed to stabilize even on 60%. Additionally, the lack of a gas filter by default will cause nitryl build up in the cooling loop which will worsen the RBMK performance over time.
![image](https://user-images.githubusercontent.com/43061493/143256057-a8120ec9-6e71-4af2-805a-818d56801817.png)

**Comment by jupyterkat** [comment]
there's no new atmos, the pr never got merged. The reactor is 1:1 with nsv, except for the nitryl part

**Comment by williamcll** [comment]
> there's no new atmos, the pr never got merged. The reactor is 1:1 with nsv, except for the nitryl part

odd, all the setups I've done that used to work does not seem to fully stabilize the RBMK anymore.

Regardless, there are some actual design flaws that makes this reactor very easy to sabotage, moreso than the supermatter, notably no nitryl filter and small cooling loop.

**Comment by TheFakeElon** [comment]
Yeah the reactor is way too unstable as it is right now. It was meant to be punishing but not *this* punishing. Engine behavior here might be different because NSV uses a different atmos system or because #3423 isn't in NSV but I'm not sure how much that matters. Nitryl is unlikely to be the cause though

**Comment by williamcll** [comment]
> Yeah the reactor is way too unstable as it is right now. It was meant to be punishing but not _this_ punishing. Engine behavior here might be different because NSV uses a different atmos system or because #3423 isn't in NSV but I'm not sure how much that matters. Nitryl is unlikely to be the cause though

I'll try more on the next atmos testmerge

**Comment by Consul99** [comment]
This isn't a bug or an issue. The reactor is coded to randomize the K at which it is stable each round. You're supposed to test it by trial and error.
I've personally never had an issue having a completely stable reactor at 100% power after 2 minutes of trial and error with the criticality.
![time2grill](https://user-images.githubusercontent.com/93437170/150775857-06d09b44-1f13-4f70-a82b-640b97bfde41.PNG)

**Comment by Consul99** [comment]
As for your set up:
You haven't got enough cooling for that level of power. You can easily produce enough power for the station without upgrading anything just like the SM. But if you want big number you'll need a few coolers.
Also using volume pumps is just asking for trouble.

**Comment by williamcll** [comment]
> As for your set up: You haven't got enough cooling for that level of power. You can easily produce enough power for the station without upgrading anything just like the SM. But if you want big number you'll need a few coolers. Also using volume pumps is just asking for trouble.

That's the problem, most setups shouldn't even need coolers to run.
